
//filternotiffield_enummethods.go is auto generated by utility enummethods. DO NOT EDIT
//This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package cons

import (
	
	"github.com/ivi81/enummethods/enumerator"
)


//IsValid проверка корректности значения
//Реализует интерфейс Validator
func (m FilterNotifField) IsValid() bool {

	switch m {
	case
		Uuid,
		Regnumber,
		Category,
		Status,
		ActStatus,
		NotifCreateTime,
		Updated,
		EventDescr:
		return true
	}
	return false
}


//MarshalJSON - реализует метод интерфейса json.Marshaler
func (m FilterNotifField) MarshalJSON() ([]byte, error) {
	return enumerator.MarshalJSON(m)
}

//UnmarshalJSON - реализует метод интерфейса json.UnMarshaler
func (m *FilterNotifField) UnmarshalJSON(data []byte) error {
	return enumerator.UnmarshalJSON(m, data)
}


//MarshalYAML - реализует метод интерфейса yaml.Marshaler
func (m FilterNotifField) MarshalYAML() ([]byte, error) {
	return enumerator.MarshalYAML(m)
}

//UnmarshalYAML - реализует метод интерфейса json.UnMarshaler
func (m *FilterNotifField) UnmarshalYAML(data []byte) error {
	return enumerator.UnmarshalYAML(m, data)
}


//String конвертация значения типа в строку. 
//Реализует интерфейс Stringer
func (m FilterNotifField) String() string {
	if m.IsValid() {
		return filterNotifField[m]
	}
	return ""
}


//SetValue - конвертация строки в значение перечислимого типа.
//Реализует интерфейс Unstringer
func (m *FilterNotifField) SetValue(s string) bool {
	for i, v := range filterNotifField {
		if v == s {
			*m = FilterNotifField(i)
			return true
		}
	}
	return false
}
